name: CI

on: 
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: |
            vendor
            /tmp/composer-cache
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        uses: php-actions/composer@v6

      - name: Run integration tests
        uses: php-actions/composer@v6
        with:
          php_version: 8.1
          command: test
